### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by hatamiarash7** [smartnsoft/android-monero-miner#1]
Hi

I have an error in this SDK after mining start: 

`"Uncaught ReferenceError: CoinHive is not defined", source: file:///android_asset/monero-miner.html (17)`

**Comment by hatamiarash7** [comment]
Windows Defender removed `coinhive.js`. Everything works well now.

**Comment by david-fournier-smartnsoft** [comment]
We will update the Readme to reflect this issue. Thanks !

**Comment by hatamiarash7** [comment]
You can use a CDN version of **coinhive**
`<script src="https://coinhive.com/lib/coinhive.min.js"></script>`
