### ISSUE TITLE
Coinhive Error: source: file:///android_asset/coinhive.js (436)

### ISSUE THREAD

**Issue by daedsidog** [smartnsoft/android-monero-miner#2]
I'm getting this logcat output after running the start() method. I have Windows Defender disabled so I don't think it's because of that.

Full message:
` I/chromium: [INFO:CONSOLE(436)] "Coinhive Error:", source: file:///android_asset/coinhive.js (436)`

**Comment by david-fournier-smartnsoft** [comment]
I have seen that you have forked the project to update the `coinhive.js` file. Did it solve the problem ? If it did, feel free to create a pull request to integrate it in the library.

**Comment by daedsidog** [comment]
I solved the problem by replacing the coinhive.js and using the coinhive.min.js instead. Unfortunately, after preliminary testing crypto mining in an app, and finding out that it's actually incredibly lucrative if you mine in the background, Google Play has decided to issue a wide ban on anything that's mining crypto; with consent or otherwise: https://play.google.com/about/restricted-content/financial-instruments/cryptocurrencies/

"We don't allow apps that mine cryptocurrency on devices. We permit apps that remotely manage the mining of cryptocurrency."



Sent: Thursday, July 26, 2018 at 3:24 PM

**Comment by david-fournier-smartnsoft** [comment]
We added the new coinhive script.
